# Use the official lightweight Python image.
# https://hub.docker.com/_/python
FROM python:3.11

# Working directory inside the container
WORKDIR /modularize_app

# Copy the content of the local src directory to the working directory
COPY . /modularize_app

# Copy the requirements.txt file into the container at /app
COPY requirements.txt ./

# Install any dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Streamlit runs on port 8501 by default, expose it
EXPOSE 8501

# Define environment variable
ENV NAME World

# Command to run on container start
CMD ["streamlit", "run", "modularize_app.py"]
